build:
	qibuild configure gcbridge -c ros-naoqi
	qibuild make gcbridge -c ros-naoqi
	#qibuild configure customlibgamectrl -c cross
	#qibuild make customlibgamectrl -c cross
clean:
	rm -rf gcbridge/build-cross/
	rm -rf gcbridge/build-sys-linux-x86_64
	#rm -rf customlibgamectrl/build-cross/
	#rm -rf customlibgamectrl/build-sys-linux-x86_64
